/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afa.login_gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author ajitrinioferi
 */
public class AddSchedule extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    public AddSchedule() {
        initComponents();
        PromptSupport.setPrompt("yyyy-mm-dd", TextField_MovieDate);
        PromptSupport.setPrompt("hh:mm:ss", TextField_ShowTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        MovieIDpanel = new javax.swing.JPanel();
        Label_title = new javax.swing.JLabel();
        ico_title = new javax.swing.JLabel();
        Label_MovieID = new javax.swing.JLabel();
        ComboBox_MovieName = new javax.swing.JComboBox<>();
        Label_StudioID = new javax.swing.JLabel();
        ComboBox_StudioName = new javax.swing.JComboBox<>();
        Label_MovieDate = new javax.swing.JLabel();
        TextField_MovieDate = new javax.swing.JTextField();
        Label_ShowTime = new javax.swing.JLabel();
        TextField_ShowTime = new javax.swing.JTextField();
        ico_Exit = new javax.swing.JLabel();
        ico_Back = new javax.swing.JLabel();
        Label_Copyright = new javax.swing.JLabel();
        Addpanel = new javax.swing.JPanel();
        btn_Add = new javax.swing.JButton();
        Label_exampleMD = new javax.swing.JLabel();
        Label_exampleST = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(405, 219));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setMinimumSize(new java.awt.Dimension(670, 410));
        bg.setPreferredSize(new java.awt.Dimension(670, 410));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovieIDpanel.setBackground(new java.awt.Color(0, 255, 51));
        MovieIDpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_title.setBackground(new java.awt.Color(204, 204, 204));
        Label_title.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Label_title.setForeground(new java.awt.Color(255, 255, 255));
        Label_title.setText("Movie Schedule");
        MovieIDpanel.add(Label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        ico_title.setForeground(new java.awt.Color(255, 255, 255));
        ico_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_schedule_127px_1.png"))); // NOI18N
        MovieIDpanel.add(ico_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -20, 120, 120));

        bg.add(MovieIDpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 560, 78));

        Label_MovieID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_MovieID.setForeground(new java.awt.Color(255, 255, 255));
        Label_MovieID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_MovieID.setText("Movie Name");
        bg.add(Label_MovieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        ComboBox_MovieName.setBackground(new java.awt.Color(0, 0, 0));
        ComboBox_MovieName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ComboBox_MovieName.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_MovieName.setMaximumRowCount(5);
        ComboBox_MovieName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        bg.add(ComboBox_MovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 30));

        Label_StudioID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_StudioID.setForeground(new java.awt.Color(255, 255, 255));
        Label_StudioID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_StudioID.setText("Studio Name");
        bg.add(Label_StudioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));

        ComboBox_StudioName.setBackground(new java.awt.Color(0, 0, 0));
        ComboBox_StudioName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ComboBox_StudioName.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_StudioName.setMaximumRowCount(5);
        ComboBox_StudioName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        ComboBox_StudioName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_StudioNameItemStateChanged(evt);
            }
        });
        bg.add(ComboBox_StudioName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 30));

        Label_MovieDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_MovieDate.setForeground(new java.awt.Color(255, 255, 255));
        Label_MovieDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_MovieDate.setText("Movie Date");
        bg.add(Label_MovieDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, -1));

        TextField_MovieDate.setBackground(new java.awt.Color(0, 0, 0));
        TextField_MovieDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_MovieDate.setForeground(new java.awt.Color(255, 255, 255));
        TextField_MovieDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_MovieDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_MovieDate.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextField_MovieDate.setOpaque(false);
        bg.add(TextField_MovieDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 30));

        Label_ShowTime.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_ShowTime.setForeground(new java.awt.Color(255, 255, 255));
        Label_ShowTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ShowTime.setText("Show Time");
        bg.add(Label_ShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 200, 220, -1));

        TextField_ShowTime.setBackground(new java.awt.Color(0, 0, 0));
        TextField_ShowTime.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_ShowTime.setForeground(new java.awt.Color(255, 255, 255));
        TextField_ShowTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_ShowTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_ShowTime.setOpaque(false);
        bg.add(TextField_ShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 220, 30));

        ico_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_delete_30px.png"))); // NOI18N
        ico_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_ExitMouseClicked(evt);
            }
        });
        bg.add(ico_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        ico_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_back_30px.png"))); // NOI18N
        ico_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_BackMouseClicked(evt);
            }
        });
        bg.add(ico_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        Label_Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_Copyright.setForeground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setText("Developed by AFA Inc.");
        bg.add(Label_Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 126, 30));

        Addpanel.setBackground(new java.awt.Color(0, 255, 51));
        Addpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddpanelMouseClicked(evt);
            }
        });

        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_plus_math_52px.png"))); // NOI18N
        btn_Add.setContentAreaFilled(false);

        javax.swing.GroupLayout AddpanelLayout = new javax.swing.GroupLayout(Addpanel);
        Addpanel.setLayout(AddpanelLayout);
        AddpanelLayout.setHorizontalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddpanelLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        AddpanelLayout.setVerticalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddpanelLayout.createSequentialGroup()
                .addComponent(btn_Add)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(Addpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 490, 60));

        Label_exampleMD.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_exampleMD.setForeground(new java.awt.Color(153, 153, 153));
        Label_exampleMD.setText("yyyy-mm-dd");
        bg.add(Label_exampleMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 220, -1));

        Label_exampleST.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_exampleST.setForeground(new java.awt.Color(153, 153, 153));
        Label_exampleST.setText("hh:mm:ss");
        bg.add(Label_exampleST, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_StudioNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_StudioNameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_StudioNameItemStateChanged

    private void ico_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ico_ExitMouseClicked

    private void ico_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_BackMouseClicked
        // TODO add your handling code here:
        ScheduleMenu x = new ScheduleMenu();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ico_BackMouseClicked

    private void AddpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddpanelMouseClicked
        // TODO add your handling code here:
        if (!TextField_MovieDate.getText().isBlank() && !TextField_MovieDate.getText().isEmpty()
                && !TextField_ShowTime.getText().isBlank() && !TextField_ShowTime.getText().isEmpty()
                && ComboBox_MovieName.getSelectedItem() != null && ComboBox_MovieName.getSelectedItem() != ""
                && ComboBox_StudioName.getSelectedItem() != null && ComboBox_StudioName.getSelectedItem() != "") {
            try {
                Schedule schedule_data = new Schedule();

                ResultSet rs;
                String string_moviedate = "";
                Date now = new Date();
                Date dateinput = new SimpleDateFormat("yyyy-MM-dd").parse(TextField_MovieDate.getText());
                String qry = "SELECT * FROM `movies` where Title = '" + (String) ComboBox_MovieName.getSelectedItem() + "';";
                rs = AFAUtils.Select(qry);
                while (rs.next()) {
                    schedule_data.setMovieID(rs.getString("MovieID"));
                    string_moviedate = rs.getString("EndDate");
                }
                qry = "SELECT * FROM `studio` where Name = '" + (String) ComboBox_StudioName.getSelectedItem() + "';";
                rs = AFAUtils.Select(qry);
                while (rs.next()) {
                    schedule_data.setStudioID(rs.getString("StudioID"));
                }
                int Jumlah = -1;
                String qry1 = "SELECT\n"
                        + "COUNT(*) AS JUMLAH\n"
                        + "FROM\n"
                        + "studio_history\n"
                        + "WHERE\n"
                        + "'" + TextField_MovieDate.getText() + " " + TextField_ShowTime.getText() + "' BETWEEN studio_history.Used AND studio_history.`Until` AND\n"
                        + "StudioID = '" + schedule_data.getStudioID() + "';";
                rs = AFAUtils.Select(qry1);
                while (rs.next()) {
                    Jumlah = rs.getInt("JUMLAH");
                }
                Date moviedate = new SimpleDateFormat("yyyy-MM-dd").parse(string_moviedate);
                if (Jumlah == 0 && dateinput.after(now) && (dateinput.before(moviedate) || dateinput.equals(moviedate)) ) {

                    // TODO add your handling code here:
                    schedule_data.setMovieDate(TextField_MovieDate.getText());
                    schedule_data.setShowtimes(TextField_ShowTime.getText());
                    String query = " insert into schedule (MovieID, StudioID, MovieDate, Showtimes)"
                            + " values (?, ?, ?, ?)";
                    PreparedStatement preparedStmt = AFAUtils.conn.prepareStatement(query);
                    preparedStmt.setString(1, schedule_data.getMovieID());
                    preparedStmt.setString(2, schedule_data.getStudioID());
                    preparedStmt.setString(3, schedule_data.getMovieDate());
                    preparedStmt.setString(4, schedule_data.getShowtimes());
                    preparedStmt.execute();
                    JOptionPane.showMessageDialog(null,
                            "Add Successfuly",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    AddSchedule x = new AddSchedule();
                    x.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Error, add please check",
                            "Success",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(AddSchedule.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(AddSchedule.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Text field cannot be blank",
                    "Failed",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AddpanelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date datenow = new Date();
        try {
            // TODO add your handling code here:
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String qry = "SELECT * FROM `movies` WHERE EndDate >= " + "'" + formatter.format(datenow) + "';";
            ResultSet rs = AFAUtils.Select(qry);
            while (rs.next()) {
                ComboBox_MovieName.addItem(rs.getString("Title"));
            }
            qry = "SELECT * FROM `studio`";
            rs = AFAUtils.Select(qry);
            while (rs.next()) {
                ComboBox_StudioName.addItem(rs.getString("Name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboBox_MovieName.setSelectedIndex(-1);
        ComboBox_StudioName.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addpanel;
    private javax.swing.JComboBox<String> ComboBox_MovieName;
    private javax.swing.JComboBox<String> ComboBox_StudioName;
    public javax.swing.JLabel Label_Copyright;
    private javax.swing.JLabel Label_MovieDate;
    private javax.swing.JLabel Label_MovieID;
    private javax.swing.JLabel Label_ShowTime;
    private javax.swing.JLabel Label_StudioID;
    private javax.swing.JLabel Label_exampleMD;
    private javax.swing.JLabel Label_exampleST;
    private javax.swing.JLabel Label_title;
    private javax.swing.JPanel MovieIDpanel;
    private javax.swing.JTextField TextField_MovieDate;
    private javax.swing.JTextField TextField_ShowTime;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Add;
    private javax.swing.JLabel ico_Back;
    private javax.swing.JLabel ico_Exit;
    private javax.swing.JLabel ico_title;
    // End of variables declaration//GEN-END:variables
}
