/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afa.login_gui;

/**
 *
 * @author ajitrinioferi
 */
public class StartMenu extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu
     */
    public StartMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        Label_SubTitle = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        ico_title = new javax.swing.JLabel();
        Panel_MovieMenu = new javax.swing.JPanel();
        ico_Movie = new javax.swing.JLabel();
        Label_MovieMenu = new javax.swing.JLabel();
        Panel_ScheduleMenu = new javax.swing.JPanel();
        ico_Schedule = new javax.swing.JLabel();
        Label_ScheduleMenu = new javax.swing.JLabel();
        Panel_ViewTransaction = new javax.swing.JPanel();
        ico_Transaction = new javax.swing.JLabel();
        Label_ViewTransaction = new javax.swing.JLabel();
        Label_Copyright = new javax.swing.JLabel();
        ico_LogOut = new javax.swing.JLabel();
        ico_Exit = new javax.swing.JLabel();
        ico_Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(345, 187));
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setBackground(new java.awt.Color(0, 255, 51));

        Label_SubTitle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_SubTitle.setForeground(new java.awt.Color(255, 255, 255));
        Label_SubTitle.setText("Main Menu");

        Label_Title.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(255, 255, 255));
        Label_Title.setText("CTS Administrator");

        ico_title.setForeground(new java.awt.Color(255, 255, 255));
        ico_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_enter_104px_2.png"))); // NOI18N

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addComponent(ico_title, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_SubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ico_title, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_SubTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 675, 89));

        Panel_MovieMenu.setBackground(new java.awt.Color(51, 51, 51));
        Panel_MovieMenu.setPreferredSize(new java.awt.Dimension(145, 145));
        Panel_MovieMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_MovieMenuMouseClicked(evt);
            }
        });

        ico_Movie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_clapperboard_52px.png"))); // NOI18N

        Label_MovieMenu.setBackground(new java.awt.Color(51, 51, 51));
        Label_MovieMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_MovieMenu.setForeground(new java.awt.Color(255, 255, 255));
        Label_MovieMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_MovieMenu.setText("Movie Menu");

        javax.swing.GroupLayout Panel_MovieMenuLayout = new javax.swing.GroupLayout(Panel_MovieMenu);
        Panel_MovieMenu.setLayout(Panel_MovieMenuLayout);
        Panel_MovieMenuLayout.setHorizontalGroup(
            Panel_MovieMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MovieMenuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ico_Movie)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(Panel_MovieMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_MovieMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_MovieMenuLayout.setVerticalGroup(
            Panel_MovieMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MovieMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ico_Movie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_MovieMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(Panel_MovieMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 120));

        Panel_ScheduleMenu.setBackground(new java.awt.Color(51, 51, 51));
        Panel_ScheduleMenu.setPreferredSize(new java.awt.Dimension(145, 145));
        Panel_ScheduleMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ScheduleMenuMouseClicked(evt);
            }
        });

        ico_Schedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_schedule_52px.png"))); // NOI18N

        Label_ScheduleMenu.setBackground(new java.awt.Color(51, 51, 51));
        Label_ScheduleMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_ScheduleMenu.setForeground(new java.awt.Color(255, 255, 255));
        Label_ScheduleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ScheduleMenu.setText("Schedule Menu");

        javax.swing.GroupLayout Panel_ScheduleMenuLayout = new javax.swing.GroupLayout(Panel_ScheduleMenu);
        Panel_ScheduleMenu.setLayout(Panel_ScheduleMenuLayout);
        Panel_ScheduleMenuLayout.setHorizontalGroup(
            Panel_ScheduleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ScheduleMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_ScheduleMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Panel_ScheduleMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ico_Schedule)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        Panel_ScheduleMenuLayout.setVerticalGroup(
            Panel_ScheduleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ScheduleMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ico_Schedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ScheduleMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(Panel_ScheduleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, 120));

        Panel_ViewTransaction.setBackground(new java.awt.Color(51, 51, 51));
        Panel_ViewTransaction.setPreferredSize(new java.awt.Dimension(145, 145));
        Panel_ViewTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ViewTransactionMouseClicked(evt);
            }
        });

        ico_Transaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_transaction_52px_1.png"))); // NOI18N

        Label_ViewTransaction.setBackground(new java.awt.Color(51, 51, 51));
        Label_ViewTransaction.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_ViewTransaction.setForeground(new java.awt.Color(255, 255, 255));
        Label_ViewTransaction.setText("View Transaction");

        javax.swing.GroupLayout Panel_ViewTransactionLayout = new javax.swing.GroupLayout(Panel_ViewTransaction);
        Panel_ViewTransaction.setLayout(Panel_ViewTransactionLayout);
        Panel_ViewTransactionLayout.setHorizontalGroup(
            Panel_ViewTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ViewTransactionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ico_Transaction)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ViewTransactionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_ViewTransaction)
                .addGap(20, 20, 20))
        );
        Panel_ViewTransactionLayout.setVerticalGroup(
            Panel_ViewTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ViewTransactionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ico_Transaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_ViewTransaction)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        bg.add(Panel_ViewTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, 120));

        Label_Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_Copyright.setForeground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setText("Developed by AFA Inc.");
        bg.add(Label_Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 126, 22));

        ico_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_logout_rounded_left_30px.png"))); // NOI18N
        ico_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_LogOutMouseClicked(evt);
            }
        });
        bg.add(ico_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        ico_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_delete_30px.png"))); // NOI18N
        ico_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_ExitMouseClicked(evt);
            }
        });
        bg.add(ico_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        ico_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_back_30px.png"))); // NOI18N
        ico_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_BackMouseClicked(evt);
            }
        });
        bg.add(ico_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_MovieMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MovieMenuMouseClicked
        // TODO add your handling code here:
        MovieMenu x = new MovieMenu();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_MovieMenuMouseClicked

    private void Panel_ScheduleMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ScheduleMenuMouseClicked
        // TODO add your handling code here:
        ScheduleMenu x = new ScheduleMenu();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_ScheduleMenuMouseClicked

    private void Panel_ViewTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ViewTransactionMouseClicked
        // TODO add your handling code here:
        TransactionView x = new TransactionView();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_ViewTransactionMouseClicked

    private void ico_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_LogOutMouseClicked
        // TODO add your handling code here:
        LogInAdm x = new LogInAdm();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ico_LogOutMouseClicked

    private void ico_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ico_ExitMouseClicked

    private void ico_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_BackMouseClicked
        // TODO add your handling code here:
        StartMenu x = new StartMenu();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ico_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Label_Copyright;
    private javax.swing.JLabel Label_MovieMenu;
    private javax.swing.JLabel Label_ScheduleMenu;
    private javax.swing.JLabel Label_SubTitle;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JLabel Label_ViewTransaction;
    private javax.swing.JPanel Panel_MovieMenu;
    private javax.swing.JPanel Panel_ScheduleMenu;
    private javax.swing.JPanel Panel_ViewTransaction;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel ico_Back;
    private javax.swing.JLabel ico_Exit;
    private javax.swing.JLabel ico_LogOut;
    private javax.swing.JLabel ico_Movie;
    private javax.swing.JLabel ico_Schedule;
    private javax.swing.JLabel ico_Transaction;
    private javax.swing.JLabel ico_title;
    // End of variables declaration//GEN-END:variables
}
