/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afa.login_gui;
import java.sql.*;
import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Iterator;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
/**
 *
 * @author ajitrinioferi
 */
public class TransactionView extends javax.swing.JFrame {

    /**
     * Creates new form TransactionView
     */
    public TransactionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        MovieIDpanel = new javax.swing.JPanel();
        Label_title = new javax.swing.JLabel();
        ico_title = new javax.swing.JLabel();
        btn_Generate = new javax.swing.JButton();
        Label_StartDate = new javax.swing.JLabel();
        TextField_StartDate = new javax.swing.JTextField();
        Label_EndDate = new javax.swing.JLabel();
        TextField_EndDate = new javax.swing.JTextField();
        Label_TotalIncome = new javax.swing.JLabel();
        TextField_TotalIncome = new javax.swing.JTextField();
        Label_TotalTicketSold = new javax.swing.JLabel();
        TextField_TotalTicketSold = new javax.swing.JTextField();
        ico_Exit = new javax.swing.JLabel();
        ico_Back = new javax.swing.JLabel();
        Label_Copyright = new javax.swing.JLabel();
        Label_StartDate1 = new javax.swing.JLabel();
        Label_StartDate2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(405, 179));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setMinimumSize(new java.awt.Dimension(670, 410));
        bg.setPreferredSize(new java.awt.Dimension(670, 410));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovieIDpanel.setBackground(new java.awt.Color(0, 255, 51));
        MovieIDpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_title.setBackground(new java.awt.Color(204, 204, 204));
        Label_title.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Label_title.setForeground(new java.awt.Color(255, 255, 255));
        Label_title.setText("Transaction View");
        MovieIDpanel.add(Label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        ico_title.setForeground(new java.awt.Color(255, 255, 255));
        ico_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_us_dollar_127px.png"))); // NOI18N
        MovieIDpanel.add(ico_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -20, 120, 120));

        bg.add(MovieIDpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 560, 78));

        btn_Generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_logout_rounded_down_127px_2.png"))); // NOI18N
        btn_Generate.setContentAreaFilled(false);
        btn_Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerateActionPerformed(evt);
            }
        });
        bg.add(btn_Generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, -1));

        Label_StartDate.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_StartDate.setForeground(new java.awt.Color(153, 153, 153));
        Label_StartDate.setText("yyyy-mm-dd");
        bg.add(Label_StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 190, -1));

        TextField_StartDate.setBackground(new java.awt.Color(0, 0, 0));
        TextField_StartDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_StartDate.setForeground(new java.awt.Color(255, 255, 255));
        TextField_StartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_StartDate.setToolTipText("Year-Month-Date");
        TextField_StartDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_StartDate.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextField_StartDate.setOpaque(false);
        bg.add(TextField_StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        Label_EndDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_EndDate.setForeground(new java.awt.Color(255, 255, 255));
        Label_EndDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_EndDate.setText("End Date");
        bg.add(Label_EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 190, -1));

        TextField_EndDate.setBackground(new java.awt.Color(0, 0, 0));
        TextField_EndDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_EndDate.setForeground(new java.awt.Color(255, 255, 255));
        TextField_EndDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_EndDate.setToolTipText("Year-Month-Date");
        TextField_EndDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_EndDate.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextField_EndDate.setOpaque(false);
        bg.add(TextField_EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 190, 30));

        Label_TotalIncome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_TotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        Label_TotalIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_TotalIncome.setText("Total Income");
        bg.add(Label_TotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, -1));

        TextField_TotalIncome.setEditable(false);
        TextField_TotalIncome.setBackground(new java.awt.Color(0, 0, 0));
        TextField_TotalIncome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_TotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        TextField_TotalIncome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_TotalIncome.setToolTipText("Cannot Input Text");
        TextField_TotalIncome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_TotalIncome.setOpaque(false);
        bg.add(TextField_TotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 190, 30));

        Label_TotalTicketSold.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_TotalTicketSold.setForeground(new java.awt.Color(255, 255, 255));
        Label_TotalTicketSold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_TotalTicketSold.setText("Total Ticket Sold");
        bg.add(Label_TotalTicketSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, -1));

        TextField_TotalTicketSold.setEditable(false);
        TextField_TotalTicketSold.setBackground(new java.awt.Color(0, 0, 0));
        TextField_TotalTicketSold.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextField_TotalTicketSold.setForeground(new java.awt.Color(255, 255, 255));
        TextField_TotalTicketSold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_TotalTicketSold.setToolTipText("Cannot Input Text");
        TextField_TotalTicketSold.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TextField_TotalTicketSold.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextField_TotalTicketSold.setOpaque(false);
        bg.add(TextField_TotalTicketSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 190, 30));

        ico_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_delete_30px.png"))); // NOI18N
        ico_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_ExitMouseClicked(evt);
            }
        });
        bg.add(ico_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        ico_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atfxgone/icons8_back_30px.png"))); // NOI18N
        ico_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_BackMouseClicked(evt);
            }
        });
        bg.add(ico_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, -1, -1));

        Label_Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_Copyright.setForeground(new java.awt.Color(204, 204, 204));
        Label_Copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Copyright.setText("Developed by AFA Inc.");
        bg.add(Label_Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 126, 40));

        Label_StartDate1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Label_StartDate1.setForeground(new java.awt.Color(255, 255, 255));
        Label_StartDate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_StartDate1.setText("Start Date");
        bg.add(Label_StartDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        Label_StartDate2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_StartDate2.setForeground(new java.awt.Color(153, 153, 153));
        Label_StartDate2.setText("yyyy-mm-dd");
        bg.add(Label_StartDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ico_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ico_ExitMouseClicked

    private void ico_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_BackMouseClicked
        // TODO add your handling code here:
        StartMenu x = new StartMenu();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ico_BackMouseClicked


    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn_GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerateActionPerformed
        try {
            String qry = "SELECT SUM(SeatsUnvailable) as TicketSold, SUM(SeatsUnvailable*Price) as Income FROM `schedule` WHERE MovieDate BETWEEN '"+TextField_StartDate.getText()+"' AND '"+TextField_EndDate.getText()+"'";
            ResultSet rs = AFAUtils.Select(qry);
            while (rs.next()) {
                TextField_TotalTicketSold.setText(rs.getString("TicketSold"));
                TextField_TotalIncome.setText(rs.getString("Income"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TransactionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_GenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Label_Copyright;
    private javax.swing.JLabel Label_EndDate;
    private javax.swing.JLabel Label_StartDate;
    private javax.swing.JLabel Label_StartDate1;
    private javax.swing.JLabel Label_StartDate2;
    private javax.swing.JLabel Label_TotalIncome;
    private javax.swing.JLabel Label_TotalTicketSold;
    private javax.swing.JLabel Label_title;
    private javax.swing.JPanel MovieIDpanel;
    private javax.swing.JTextField TextField_EndDate;
    private javax.swing.JTextField TextField_StartDate;
    private javax.swing.JTextField TextField_TotalIncome;
    private javax.swing.JTextField TextField_TotalTicketSold;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Generate;
    private javax.swing.JLabel ico_Back;
    private javax.swing.JLabel ico_Exit;
    private javax.swing.JLabel ico_title;
    // End of variables declaration//GEN-END:variables
}
